resources:
  '*':
    limits:
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-4.10
  cluster_claim:
    architecture: amd64
    cloud: aws
    owner: rhecoedge-nvidia-ci
    product: ocp
    timeout: 1h0m0s
    version: "4.10"
  steps:
    test:
    - as: claim
      commands: |
        oc version
      from: stable-latest:cli
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
zz_generated_metadata:
  branch: main
  org: rh-ecosystem-edge
  repo: nvidia-ci
